source "https://rubygems.org"
gem "jekyll", "~> 3.5.0"
gem "jekyll-theme-minimal"
gem "jekyll-theme-dinky"
gem "jekyll-theme-cayman"
gem "jekyll-theme-architect"
gem "jekyll-theme-hacker"
gem "jekyll-theme-midnight"
gem "jekyll-theme-slate"
gem "jekyll-theme-primer"
gem "jekyll-theme-tactile"
gem "jekyll-theme-modernist"
gem "jekyll-theme-leap-day"
gem "jekyll-theme-time-machine"
gem "bundler", "~> 2.4"
gem "jekyll-seo-tag", "~> 2.1.0"
gem "pathutil", "~> 0.11.0"
gem "rexml"
gem "bootstrap", "~>4.6.0"
gem "jekyll-readme-index", "~> 0.3.0"
